frameworkVersion: '3'
service: serverless-stack-python-starter

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: false

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: us-east-1
  memorySize: 256
  timeout: 10

package:
  patterns:
    - '!node_modules/**'
    - '!test/**'
    - '!tests/**'
    - '!README.md'

functions:
  hello:
    handler: handler.hello
    memorySize: 256
    timeout: 10
    events:
      - httpApi:
          path: /
          method: get