frameworkVersion: '3'
<<<<<<< Updated upstream

=======
>>>>>>> Stashed changes
service: serverless-stack-python-starter

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: us-east-1
  memorySize: 128
  timeout: 10

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: false

<<<<<<< Updated upstream
package:
  patterns:
    - '!tests/**'
    - '!test/**'
    - '!README*'
    - '!docs/**'
    - '!node_modules/**'
    - '!package-lock.json'
    - '!serverless.yml'
=======
provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: us-east-1
  httpApi:
    cors: true
>>>>>>> Stashed changes

functions:
  hello:
    handler: handler.hello
    memorySize: 128
    timeout: 10
    events:
      - httpApi:
          path: /
<<<<<<< Updated upstream
          method: get
=======
          method: get

package:
  patterns:
    - '!node_modules/**'
    - '!test/**'
    - '!tests/**'
    - '!*.md'
    - '!*.log'
    - '**/*'
>>>>>>> Stashed changes
