frameworkVersion: '3'
service: serverless-stack-python-starter

plugins:
  - serverless-python-requirements@^6.0.0

custom:
  pythonRequirements:
    dockerizePip: false

provider:
  name: aws
  runtime: python3.9
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

package:
  individually: true
  patterns:
    - '!test/**'
    - '!tests/**'
    - '!__pycache__/**'
    - '!*.pyc'
    - '!*.pyo'
    - '!*.dist-info/**'

functions:
  hello:
    handler: handler.hello
    memorySize: 128
    timeout: 10
    events:
      - httpApi:
          path: /
          method: get