frameworkVersion: '3'
service: serverless-stack-python-starter

plugins:
  - serverless-python-requirements@^3.0.9

custom:
  pythonRequirements:
    dockerizePip: false

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: us-east-1
  memorySize: 512
  timeout: 10

package:
  patterns:
    - '!node_modules/**'
    - '!tests/**'
    - '!*.md'
    - '!requirements.txt'
    - '!package.json'
    - '!package-lock.json'

functions:
  hello:
    handler: handler.hello
    memorySize: 128
    timeout: 5
    events:
      - httpApi:
          path: /
          method: get