frameworkVersion: '3'

service: serverless-stack-python-starter

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: false

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: us-east-1
  httpApi:
    cors: true

functions:
  hello:
    handler: handler.hello
    memorySize: 128
    timeout: 10
    events:
      - httpApi:
          path: /
          method: get

package:
  patterns:
    - '!test/**'
    - '!tests/**'
    - '!__pycache__/**'
    - '!node_modules/**'
    - '!*.md'
    - '!*.log'
    - '!package-lock.json'
    - '!yarn.lock'
    - '!venv/**'
    - '**'