frameworkVersion: '3'

service: serverless-stack-python-starter

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: us-east-1
  memorySize: 128
  timeout: 10

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: false

package:
  patterns:
    - '!tests/**'
    - '!test/**'
    - '!README*'
    - '!docs/**'
    - '!node_modules/**'
    - '!package-lock.json'
    - '!serverless.yml'

functions:
  hello:
    handler: handler.hello
    memorySize: 128
    timeout: 10
    events:
      - httpApi:
          path: /
          method: get